import { Address } from "./types";

export const mockAddresses: Address[] = [
  {
    id: "1",
    name: "John Doe",
    phone: "+1 (555) 123-4567",
    street: "123 Main Street, Apt 4B",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    country: "United States",
    isDefault: true,
    label: "Home",
  },
  {
    id: "2",
    name: "John Doe",
    phone: "+1 (555) 123-4567",
    street: "456 Oak Avenue",
    city: "Brooklyn",
    state: "NY",
    zipCode: "11201",
    country: "United States",
    isDefault: false,
    label: "Work",
  },
  {
    id: "3",
    name: "Sarah Doe",
    phone: "+1 (555) 987-6543",
    street: "789 Pine Road, Suite 200",
    city: "Los Angeles",
    state: "CA",
    zipCode: "90001",
    country: "United States",
    isDefault: false,
    label: "Other",
  },
  {
    id: "4",
    name: "Michael Smith",
    phone: "+1 (555) 456-7890",
    street: "321 Elm Street",
    city: "Chicago",
    state: "IL",
    zipCode: "60601",
    country: "United States",
    isDefault: false,
    label: "Home",
  },
  {
    id: "5",
    name: "Emily Johnson",
    phone: "+1 (555) 234-5678",
    street: "654 Maple Drive, Unit 12",
    city: "Seattle",
    state: "WA",
    zipCode: "98101",
    country: "United States",
    isDefault: false,
    label: "Work",
  },
];

export const addressLabels = [
  { value: "Home", label: "Home" },
  { value: "Work", label: "Work" },
  { value: "Other", label: "Other" },
] as const;

export const usStates = [
  { value: "AL", label: "Alabama" },
  { value: "AK", label: "Alaska" },
  { value: "AZ", label: "Arizona" },
  { value: "AR", label: "Arkansas" },
  { value: "CA", label: "California" },
  { value: "CO", label: "Colorado" },
  { value: "CT", label: "Connecticut" },
  { value: "DE", label: "Delaware" },
  { value: "FL", label: "Florida" },
  { value: "GA", label: "Georgia" },
  { value: "HI", label: "Hawaii" },
  { value: "ID", label: "Idaho" },
  { value: "IL", label: "Illinois" },
  { value: "IN", label: "Indiana" },
  { value: "IA", label: "Iowa" },
  { value: "KS", label: "Kansas" },
  { value: "KY", label: "Kentucky" },
  { value: "LA", label: "Louisiana" },
  { value: "ME", label: "Maine" },
  { value: "MD", label: "Maryland" },
  { value: "MA", label: "Massachusetts" },
  { value: "MI", label: "Michigan" },
  { value: "MN", label: "Minnesota" },
  { value: "MS", label: "Mississippi" },
  { value: "MO", label: "Missouri" },
  { value: "MT", label: "Montana" },
  { value: "NE", label: "Nebraska" },
  { value: "NV", label: "Nevada" },
  { value: "NH", label: "New Hampshire" },
  { value: "NJ", label: "New Jersey" },
  { value: "NM", label: "New Mexico" },
  { value: "NY", label: "New York" },
  { value: "NC", label: "North Carolina" },
  { value: "ND", label: "North Dakota" },
  { value: "OH", label: "Ohio" },
  { value: "OK", label: "Oklahoma" },
  { value: "OR", label: "Oregon" },
  { value: "PA", label: "Pennsylvania" },
  { value: "RI", label: "Rhode Island" },
  { value: "SC", label: "South Carolina" },
  { value: "SD", label: "South Dakota" },
  { value: "TN", label: "Tennessee" },
  { value: "TX", label: "Texas" },
  { value: "UT", label: "Utah" },
  { value: "VT", label: "Vermont" },
  { value: "VA", label: "Virginia" },
  { value: "WA", label: "Washington" },
  { value: "WV", label: "West Virginia" },
  { value: "WI", label: "Wisconsin" },
  { value: "WY", label: "Wyoming" },
] as const;
